<a href="https://colab.research.google.com/github/ancyjohn-726/Assessment_2_AncyJohn/blob/main/Assessment2_Numpy_%26_Pandas_AncyJohn.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

SECTION A

In [6]:
# Q1. NumPy Array Creation

import numpy as np
array_1=np.array([10,20,30,40,50])
print("The array:",array_1)
print("Shape of the array:",array_1.shape)
print("Data type of the array:",array_1.dtype)

The array: [10 20 30 40 50]
Shape of the array: (5,)
Data type of the array: int64

In [5]:
# Q2. NumPy Array Operations

array_2=np.array([5,10,15,20,25])
added_array=array_2 + 5
multiplied_array=array_2 * 2
print("Original Array:",array_2)
print("After adding 5:",added_array)
print("After multiplying by 2:",multiplied_array)

Original Array: [ 5 10 15 20 25]
After adding 5: [10 15 20 25 30]
After multiplying by 2: [10 20 30 40 50]

In [9]:
# Q3. NumPy Statistical Operations

array_3=np.array([12,15,18,20,25,30])
mean_value=np.mean(array_3)
median_value=np.median(array_3)
min_value=np.min(array_3)
max_value=np.max(array_3)
std_value=np.std(array_3)
print(f"Mean: {mean_value}")
print(f"Median: {median_value}")
print(f"Minimum: {min_value}")
print(f"Maximum: {max_value}")
print(f"Standard deviation: {std_value:.4f}")

Mean: 20.0
Median: 19.0
Minimum: 12
Maximum: 30
Standard deviation: 6.0277

In [19]:
# Q4. NumPy Filtering

array_4=np.array([10,25,30,45,50,65,70])
filtered_array=array_4[array_4 > 40]
print("Value greater than 40:",filtered_array)

Value greater than 40: [45 50 65 70]

In [14]:
# Q5. Create a Pandas DataFrame

import pandas as pd
data={'Name':['Anu','Rahul','Meera','Arun'],
      'Age':[21,22,20,23],
      'Score':[85,72,91,68]}
df=pd.DataFrame(data)
df

    Name  Age  Score
0    Anu   21     85
1  Rahul   22     72
2  Meera   20     91
3   Arun   23     68

In [26]:
# Q6. DataFrame Selection

print("Name and Score columns:\n")
print(df[['Name','Score']])
print("\nComplete record of Meera:\n")
print(df[df['Name']=='Meera'])

Name and Score columns:

    Name  Score
0    Anu     85
1  Rahul     72
2  Meera     91
3   Arun     68

Complete record of Meera:

    Name  Age  Score
2  Meera   20     91

In [27]:
# Q7. DataFrame Filtering

print("Students with Score greater than 75:\n")
print(df[df['Score']>75])

Students with Score greater than 75:

    Name  Age  Score
0    Anu   21     85
2  Meera   20     91

In [31]:
# Q8. DataFrame Inspection

print("Number of rows and columns:\n")
print(df.shape)
print("\nColumn names:\n")
print(df.columns.tolist())
print("\nData types:\n")
print(df.dtypes)
print("\nBasic statistical summary:")
print(df.describe())

Number of rows and columns:

(4, 3)

Column names:

['Name', 'Age', 'Score']

Data types:

Name     object
Age       int64
Score     int64
dtype: object

Basic statistical summary:
             Age      Score
count   4.000000   4.000000
mean   22.000000  79.000000
std     1.825742  10.801234
min    20.000000  68.000000
25%    20.750000  71.000000
50%    22.000000  78.500000
75%    23.250000  86.500000
max    24.000000  91.000000

In [32]:
# Q9. Sorting a DataFrame

df_sorted=df.sort_values(by='Score',ascending=False)
df_sorted

    Name  Age  Score
2  Meera   20     91
0    Anu   21     85
1  Rahul   24     72
3   Arun   23     68

In [37]:
# Q10. Handling Missing Values

df_missing=pd.DataFrame({'Name': ['A', 'B', 'C', 'D'],
                         'Age': [21, np.nan, 23, 22],
                         'Score': [80, 75, np.nan, 90]})
df_missing['Age']=df_missing['Age'].fillna(df_missing['Age'].mean())
df_missing['Score']=df_missing['Score'].fillna(df_missing['Score'].mean())
print("DataFrame After added missing value\n")
print(df_missing)

DataFrame After added missing value

  Name   Age      Score
0    A  21.0  80.000000
1    B  22.0  75.000000
2    C  23.0  81.666667
3    D  22.0  90.000000

SECTION B

In [45]:
# Q11. Data Loading and Exploration

df_students=pd.read_csv('/content/student_performance.csv')
print("First 5 Records :\n")
print(df_students.head(5))
print("\nLast 5 Records :\n")
print(df_students.tail(5))
print(f"\nNumber of rows and columns :\n\n{df_students.shape[0]} rows, {df_students.shape[1]} columns")
print("\nColumn Names :\n\n", df_students.columns.tolist())
print("\nData Types :\n")
print(df_students.dtypes)
print("\nStatistical Summary :\n")
print(df_students.describe())

First 5 Records :

  Student_ID            Name  Gender        Department   Age  Attendance  \
0    STU1001     Rahul Varma    Male  Computer Science  25.0        74.7
1    STU1002    Kiran Pillai    Male  Computer Science  24.0        75.5
2    STU1003  Fathima Joseph  Female       Electronics  21.0        60.5
3    STU1004    Rahul Sharma  Female      Data Science  25.0        80.4
4    STU1005       Asha Nair  Female      Data Science  22.0        71.4

   Python_Score  SQL_Score  Pandas_Score  NumPy_Score  Final_Score
0          89.4       86.3          81.9         76.7         82.7
1          70.3       63.1          65.1         62.3         60.3
2          79.9       80.4          65.3         68.0         67.1
3          65.8       50.7          52.6         48.8         57.2
4          90.1       82.9          72.4         87.7         81.9

Last 5 Records :

   Student_ID            Name  Gender        Department   Age  Attendance  \
75    STU1076     Priya Kumar  Female  Computer Science  24.0        99.3
76    STU1077      Amal Kumar    Male      Data Science   NaN        93.8
77    STU1078  Fathima Sharma    Male  Computer Science  19.0        86.4
78    STU1079    Meera Thomas    Male       Electronics  23.0        99.4
79    STU1080      Diya Varma    Male       Electronics  19.0        86.4

    Python_Score  SQL_Score  Pandas_Score  NumPy_Score  Final_Score
75          46.9       57.6          29.5         57.1         47.2
76          45.8       43.4          58.1         38.8         43.5
77          70.4       75.7          98.2         76.7         75.2
78          64.6       66.5          61.8         52.5         63.4
79          80.5       94.3          58.6         74.9         78.6

Number of rows and columns :

80 rows, 11 columns

Column Names :

 ['Student_ID', 'Name', 'Gender', 'Department', 'Age', 'Attendance', 'Python_Score', 'SQL_Score', 'Pandas_Score', 'NumPy_Score', 'Final_Score']

Data Types :

Student_ID       object
Name             object
Gender           object
Department       object
Age             float64
Attendance      float64
Python_Score    float64
SQL_Score       float64
Pandas_Score    float64
NumPy_Score     float64
Final_Score     float64
dtype: object

Statistical Summary :

             Age  Attendance  Python_Score   SQL_Score  Pandas_Score  \
count  77.000000   77.000000     78.000000   80.000000     78.000000
mean   22.012987   81.672727     72.821795   70.445000     70.365385
std     2.155126   10.054204     16.722103   14.630417     15.814294
min    19.000000   56.300000     39.500000   38.300000     25.000000
25%    20.000000   75.500000     64.525000   60.650000     61.800000
50%    22.000000   81.100000     72.000000   69.300000     70.000000
75%    24.000000   86.400000     86.525000   81.150000     82.575000
max    25.000000  100.000000    100.000000  100.000000    100.000000

       NumPy_Score  Final_Score
count    78.000000    78.000000
mean     68.574359    70.696154
std      16.417242    14.053871
min      25.000000    40.600000
25%      57.175000    60.450000
50%      70.700000    70.950000
75%      80.650000    82.275000
max     100.000000    97.000000

In [47]:
# Q12. Filtering and Sorting

final_score_75=df_students[df_students['Final_Score']>75]
print("Students with Final_Score greater than 75:\n")
print(final_score_75)
attendance_75=df_students[df_students['Attendance']<75]
print("\nStudents with Attendance less than 75:\n")
print(attendance_75)
data_science_students=df_students[(df_students['Department']=='Data Science') & (df_students['Final_Score']>80)]
print("\nData Science students with Final_Score greater than 80:\n")
print(data_science_students)
sorted_students=df_students.sort_values(by='Final_Score',ascending=False)
print("\nSorted Students by Final_Score:\n")
print(sorted_students)

Students with Final_Score greater than 75:

   Student_ID            Name  Gender        Department   Age  Attendance  \
0     STU1001     Rahul Varma    Male  Computer Science  25.0        74.7
4     STU1005       Asha Nair  Female      Data Science  22.0        71.4
6     STU1007     Akhil Varma    Male       Electronics  22.0        73.2
7     STU1008     Akhil Varma    Male  Computer Science  20.0        81.1
8     STU1009      Diya Menon    Male      Data Science  25.0        64.4
10    STU1011        Diya Das  Female      Data Science  20.0       100.0
11    STU1012      Arun Reddy    Male       Electronics  20.0        69.1
16    STU1017    Rahul Thomas  Female      Data Science  25.0        78.3
17    STU1018      Priya Nair    Male      Data Science  19.0        85.4
23    STU1024  Fathima Joseph  Female          Commerce  23.0        78.2
24    STU1025     Kiran Varma  Female       Electronics  21.0        80.7
27    STU1028     Nikhil Nair  Female      Data Science  24.0        79.3
30    STU1031      Amal Varma  Female  Computer Science  19.0        86.7
33    STU1034        Amal Das    Male  Computer Science  19.0        85.5
35    STU1036      Maya Menon  Female       Electronics  19.0        82.0
37    STU1038    Kiran Pillai  Female       Electronics  25.0        85.2
39    STU1040    Rohan Sharma  Female  Computer Science  21.0       100.0
40    STU1041     Amal Pillai  Female  Computer Science  25.0        97.7
41    STU1042     Arun Joseph  Female  Computer Science  21.0        85.9
43    STU1044       Rahul Das  Female  Computer Science  22.0        70.9
47    STU1048     Priya Kumar    Male      Data Science  25.0        64.6
48    STU1049     Asha Sharma    Male      Data Science  22.0        91.3
51    STU1052      Gokul Nair  Female          Commerce  25.0        77.3
55    STU1056     Vivek Varma    Male      Data Science  22.0        81.0
56    STU1057    Rohan Pillai  Female          Commerce  20.0        79.5
57    STU1058     Diya Thomas  Female  Computer Science  23.0        83.5
58    STU1059       Anu Menon    Male       Electronics  24.0        96.7
59    STU1060      Asha Menon    Male      Data Science  19.0        56.3
61    STU1062    Kiran Pillai  Female  Computer Science  19.0        83.8
64    STU1065    Rohan Sharma    Male  Computer Science  19.0        64.4
67    STU1068        Maya Das  Female  Computer Science  23.0        66.7
73    STU1074       Anu Kumar  Female  Computer Science  22.0        95.0
77    STU1078  Fathima Sharma    Male  Computer Science  19.0        86.4
79    STU1080      Diya Varma    Male       Electronics  19.0        86.4

    Python_Score  SQL_Score  Pandas_Score  NumPy_Score  Final_Score
0           89.4       86.3          81.9         76.7         82.7
4           90.1       82.9          72.4         87.7         81.9
6           81.7       82.2          81.5         64.2         77.0
7           72.1       80.4          72.9         73.5         79.2
8           94.8       86.0          87.7        100.0         83.0
10         100.0       93.2         100.0         89.3         91.9
11          80.4       78.0          88.9         77.1         86.9
16          80.8       99.4          77.2        100.0         91.1
17          62.6       81.6          79.6         75.5         75.1
23          87.7       71.0          88.5         74.8         83.7
24          87.5       67.1          84.5         96.1         77.3
27          70.3       82.0          64.4         72.8         77.1
30          86.9       64.3         100.0         89.2         85.5
33          94.4       81.6          71.3         81.5         84.3
35          95.3       93.4         100.0         62.5         84.2
37          87.8       78.3          85.5         82.7         82.4
39          68.9       79.8          66.1         66.4         78.5
40          94.3       91.0          73.1         91.2         94.5
41          71.2       76.1          70.8          NaN         77.9
43          68.0       67.3          83.6         76.7         77.3
47          80.6       67.0          71.2         80.2         77.3
48          88.9       95.0           NaN         94.5         97.0
51          80.4       85.3          96.7         83.5         79.3
55          87.0       95.1          88.4         75.7         93.3
56          72.1       66.9          61.8         72.3         75.2
57          93.1       78.8          91.6         83.8         92.3
58          99.7       77.1          68.9         89.7         84.9
59         100.0       85.0          87.4         57.4         87.9
61         100.0      100.0          89.4         91.4         96.0
64          96.5       69.3          86.7         80.7         83.5
67          83.4       79.6          89.3         83.6         83.7
73          95.3       67.7          92.4         81.4         83.4
77          70.4       75.7          98.2         76.7         75.2
79          80.5       94.3          58.6         74.9         78.6

Students with Attendance less than 75:

   Student_ID            Name    Gender        Department   Age  Attendance  \
0     STU1001     Rahul Varma      Male  Computer Science  25.0        74.7
2     STU1003  Fathima Joseph    Female       Electronics  21.0        60.5
4     STU1005       Asha Nair    Female      Data Science  22.0        71.4
6     STU1007     Akhil Varma      Male       Electronics  22.0        73.2
8     STU1009      Diya Menon      Male      Data Science  25.0        64.4
9     STU1010    Gokul Pillai    Female  Computer Science  19.0        67.3
11    STU1012      Arun Reddy      Male       Electronics  20.0        69.1
15    STU1016    Nikhil Kumar    Female  Computer Science   NaN        70.3
19    STU1020    Vivek Sharma    Female          Commerce  22.0        72.1
25    STU1026      Maya Menon      Male       Electronics  20.0        68.3
36    STU1037    Nikhil Menon      Male       Electronics  22.0        74.8
42    STU1043     Sneha Varma   female       Data Science  19.0        74.4
43    STU1044       Rahul Das    Female  Computer Science  22.0        70.9
47    STU1048     Priya Kumar      Male      Data Science  25.0        64.6
50    STU1051     Gokul Menon      Male      Data Science  25.0        70.9
59    STU1060      Asha Menon      Male      Data Science  19.0        56.3
64    STU1065    Rohan Sharma      Male  Computer Science  19.0        64.4
67    STU1068        Maya Das    Female  Computer Science  23.0        66.7
71    STU1072    Vivek Pillai      Male          Commerce  24.0        71.5

    Python_Score  SQL_Score  Pandas_Score  NumPy_Score  Final_Score
0           89.4       86.3          81.9         76.7         82.7
2           79.9       80.4          65.3         68.0         67.1
4           90.1       82.9          72.4         87.7         81.9
6           81.7       82.2          81.5         64.2         77.0
8           94.8       86.0          87.7        100.0         83.0
9           79.6       85.0          74.1         80.5         73.8
11          80.4       78.0          88.9         77.1         86.9
15          55.9       69.3          67.1         58.4         58.2
19          65.8       60.9          49.8         44.8         54.6
25          91.7       64.5          83.5         73.7         69.4
36          69.5       60.7          64.6         81.6         69.1
42          71.8       79.1          69.8         95.9          NaN
43          68.0       67.3          83.6         76.7         77.3
47          80.6       67.0          71.2         80.2         77.3
50          68.6       81.0          64.0         63.0         70.5
59         100.0       85.0          87.4         57.4         87.9
64          96.5       69.3          86.7         80.7         83.5
67          83.4       79.6          89.3         83.6         83.7
71          59.0       58.2          56.3         48.9         56.6

Data Science students with Final_Score greater than 80:

   Student_ID          Name  Gender    Department   Age  Attendance  \
4     STU1005     Asha Nair  Female  Data Science  22.0        71.4
8     STU1009    Diya Menon    Male  Data Science  25.0        64.4
10    STU1011      Diya Das  Female  Data Science  20.0       100.0
16    STU1017  Rahul Thomas  Female  Data Science  25.0        78.3
48    STU1049   Asha Sharma    Male  Data Science  22.0        91.3
55    STU1056   Vivek Varma    Male  Data Science  22.0        81.0
59    STU1060    Asha Menon    Male  Data Science  19.0        56.3

    Python_Score  SQL_Score  Pandas_Score  NumPy_Score  Final_Score
4           90.1       82.9          72.4         87.7         81.9
8           94.8       86.0          87.7        100.0         83.0
10         100.0       93.2         100.0         89.3         91.9
16          80.8       99.4          77.2        100.0         91.1
48          88.9       95.0           NaN         94.5         97.0
55          87.0       95.1          88.4         75.7         93.3
59         100.0       85.0          87.4         57.4         87.9

Sorted Students by Final_Score:

   Student_ID           Name    Gender        Department   Age  Attendance  \
48    STU1049    Asha Sharma      Male      Data Science  22.0        91.3
61    STU1062   Kiran Pillai    Female  Computer Science  19.0        83.8
40    STU1041    Amal Pillai    Female  Computer Science  25.0        97.7
55    STU1056    Vivek Varma      Male      Data Science  22.0        81.0
57    STU1058    Diya Thomas    Female  Computer Science  23.0        83.5
..        ...            ...       ...               ...   ...         ...
34    STU1035   Rahul Pillai    Female      Data Science  22.0        82.5
76    STU1077     Amal Kumar      Male      Data Science   NaN        93.8
26    STU1027  Aditya Pillai    Female  Computer Science  25.0        79.6
42    STU1043    Sneha Varma   female       Data Science  19.0        74.4
53    STU1054    Maya Sharma      Male      Data Science  19.0        82.5

    Python_Score  SQL_Score  Pandas_Score  NumPy_Score  Final_Score
48          88.9       95.0           NaN         94.5         97.0
61         100.0      100.0          89.4         91.4         96.0
40          94.3       91.0          73.1         91.2         94.5
55          87.0       95.1          88.4         75.7         93.3
57          93.1       78.8          91.6         83.8         92.3
..           ...        ...           ...          ...          ...
34          41.4       44.4          53.8         43.2         44.2
76          45.8       43.4          58.1         38.8         43.5
26          44.0       52.5          25.0         25.0         40.6
42          71.8       79.1          69.8         95.9          NaN
53          59.7       60.5          65.8         73.3          NaN

[80 rows x 11 columns]

In [48]:
# Q13. Feature Creation

new_column=['Python_Score','SQL_Score','Pandas_Score','NumPy_Score']
df_students['Average_Technical_Score']=df_students[new_column].mean(axis=1)
def performance(score):
    if score >=90:
        return 'Excellent'
    elif score >=75:
        return 'Good'
    elif score >=60:
        return 'Average'
    else:
        return 'Needs Improvement'
df_students['Performance']=df_students['Average_Technical_Score'].apply(performance)
print(df_students[['Name','Average_Technical_Score','Performance']].head())

             Name  Average_Technical_Score        Performance
0     Rahul Varma                   83.575               Good
1    Kiran Pillai                   65.200            Average
2  Fathima Joseph                   73.400            Average
3    Rahul Sharma                   54.475  Needs Improvement
4       Asha Nair                   83.275               Good

In [49]:
# Q14. GroupBy Analysis

grouped_df=df_students.groupby('Department').agg({'Name':'count','Final_Score':['mean','max','min']})
grouped_df.columns=['Number_of_Students','Average_Final_Score','Maximum_Final_Score','Minimum_Final_Score']
sorted_df=grouped_df.sort_values(by='Average_Final_Score',ascending=False)
print(sorted_df)

                  Number_of_Students  Average_Final_Score  \
Department
Electronics                       13            72.846154
Computer Science                  29            71.479310
Data Science                      27            71.324000
Commerce                           8            67.825000
data science                       1            66.900000
 Data Science                      1            55.100000
Computer science                   1            46.700000

                  Maximum_Final_Score  Minimum_Final_Score
Department
Electronics                      86.9                 51.2
Computer Science                 96.0                 40.6
Data Science                     97.0                 43.5
Commerce                         83.7                 54.6
data science                     66.9                 66.9
 Data Science                    55.1                 55.1
Computer science                 46.7                 46.7

In [70]:
# Q15. NumPy and Pandas Integration

scores = df_students["Final_Score"].dropna().values
print("Mean:\n", scores.mean())
print("\nMedian:\n", np.median(scores))
print("\nStandard Deviation:\n", scores.std())
print("\n25th Percentile:\n", np.percentile(scores, 25))
print("\n75th Percentile:\n", np.percentile(scores, 75))
print("\nStudents with Final_Score above the overall mean:\n")
display(df_students[df_students["Final_Score"] > scores.mean()])

Mean:
 70.69615384615383

Median:
 70.95

Standard Deviation:
 13.96349124578818

25th Percentile:
 60.449999999999996

75th Percentile:
 82.275

Students with Final_Score above the overall mean:

,Student_ID,Name,Gender,Department,Age,Attendance,Python_Score,SQL_Score,Pandas_Score,NumPy_Score,Final_Score,Average_Technical_Score,Performance
0,STU1001,Rahul Varma,Male,Computer Science,25.0,74.7,89.4,86.3,81.9,76.7,82.7,83.575,Good
4,STU1005,Asha Nair,Female,Data Science,22.0,71.4,90.1,82.9,72.4,87.7,81.9,83.275,Good
6,STU1007,Akhil Varma,Male,Electronics,22.0,73.2,81.7,82.2,81.5,64.2,77.0,77.400,Good
7,STU1008,Akhil Varma,Male,Computer Science,20.0,81.1,72.1,80.4,72.9,73.5,79.2,74.725,Average
8,STU1009,Diya Menon,Male,Data Science,25.0,64.4,94.8,86.0,87.7,100.0,83.0,92.125,Excellent
9,STU1010,Gokul Pillai,Female,Computer Science,19.0,67.3,79.6,85.0,74.1,80.5,73.8,79.800,Good
10,STU1011,Diya Das,Female,Data Science,20.0,100.0,100.0,93.2,100.0,89.3,91.9,95.625,Excellent
11,STU1012,Arun Reddy,Male,Electronics,20.0,69.1,80.4,78.0,88.9,77.1,86.9,81.100,Good
16,STU1017,Rahul Thomas,Female,Data Science,25.0,78.3,80.8,99.4,77.2,100.0,91.1,89.350,Good
17,STU1018,Priya Nair,Male,Data Science,19.0,85.4,62.6,81.6,79.6,75.5,75.1,74.825,Average
20,STU1021,Arun Varma,Female,Commerce,25.0,79.5,NaN,67.6,74.3,75.3,73.2,72.400,Average
23,STU1024,Fathima Joseph,Female,Commerce,23.0,78.2,87.7,71.0,88.5,74.8,83.7,80.500,Good
24,STU1025,Kiran Varma,Female,Electronics,21.0,80.7,87.5,67.1,84.5,96.1,77.3,83.800,Good
27,STU1028,Nikhil Nair,Female,Data Science,24.0,79.3,70.3,82.0,64.4,72.8,77.1,72.375,Average
30,STU1031,Amal Varma,Female,Computer Science,19.0,86.7,86.9,64.3,100.0,89.2,85.5,85.100,Good
33,STU1034,Amal Das,Male,Computer Science,19.0,85.5,94.4,81.6,71.3,81.5,84.3,82.200,Good
35,STU1036,Maya Menon,Female,Electronics,19.0,82.0,95.3,93.4,100.0,62.5,84.2,87.800,Good
37,STU1038,Kiran Pillai,Female,Electronics,25.0,85.2,87.8,78.3,85.5,82.7,82.4,83.575,Good
39,STU1040,Rohan Sharma,Female,Computer Science,21.0,100.0,68.9,79.8,66.1,66.4,78.5,70.300,Average
40,STU1041,Amal Pillai,Female,Computer Science,25.0,97.7,94.3,91.0,73.1,91.2,94.5,87.400,Good
41,STU1042,Arun Joseph,Female,Computer Science,21.0,85.9,71.2,76.1,70.8,NaN,77.9,72.700,Average
43,STU1044,Rahul Das,Female,Computer Science,22.0,70.9,68.0,67.3,83.6,76.7,77.3,73.900,Average
46,STU1047,Gokul Das,Male,Data Science,21.0,NaN,69.5,59.3,75.2,75.2,74.8,69.800,Average
47,STU1048,Priya Kumar,Male,Data Science,25.0,64.6,80.6,67.0,71.2,80.2,77.3,74.750,Average
48,STU1049,Asha Sharma,Male,Data Science,22.0,91.3,88.9,95.0,NaN,94.5,97.0,92.800,Excellent
51,STU1052,Gokul Nair,Female,Commerce,25.0,77.3,80.4,85.3,96.7,83.5,79.3,86.475,Good
52,STU1053,Maya Varma,Male,Computer Science,22.0,84.6,71.9,73.4,70.0,67.2,71.0,70.625,Average
55,STU1056,Vivek Varma,Male,Data Science,22.0,81.0,87.0,95.1,88.4,75.7,93.3,86.550,Good
56,STU1057,Rohan Pillai,Female,Commerce,20.0,79.5,72.1,66.9,61.8,72.3,75.2,68.275,Average
57,STU1058,Diya Thomas,Female,Computer Science,23.0,83.5,93.1,78.8,91.6,83.8,92.3,86.825,Good
58,STU1059,Anu Menon,Male,Electronics,24.0,96.7,99.7,77.1,68.9,89.7,84.9,83.850,Good
59,STU1060,Asha Menon,Male,Data Science,19.0,56.3,100.0,85.0,87.4,57.4,87.9,82.450,Good
60,STU1061,Fathima Sharma,Male,Computer Science,24.0,79.6,80.8,63.1,71.1,67.9,70.8,70.725,Average
61,STU1062,Kiran Pillai,Female,Computer Science,19.0,83.8,100.0,100.0,89.4,91.4,96.0,95.200,Excellent
64,STU1065,Rohan Sharma,Male,Computer Science,19.0,64.4,96.5,69.3,86.7,80.7,83.5,83.300,Good
66,STU1067,Rahul Thomas,Male,Data Science,NaN,99.3,NaN,56.2,69.0,81.5,70.7,68.900,Average
67,STU1068,Maya Das,Female,Computer Science,23.0,66.7,83.4,79.6,89.3,83.6,83.7,83.975,Good
72,STU1073,Swathi Joseph,Male,Data Science,22.0,78.7,76.4,77.5,73.6,65.6,73.5,73.275,Average
73,STU1074,Anu Kumar,Female,Computer Science,22.0,95.0,95.3,67.7,92.4,81.4,83.4,84.200,Good
74,STU1075,Gokul Nair,Female,Data Science,23.0,87.8,85.4,80.0,65.2,70.4,70.9,75.250,Good
77,STU1078,Fathima Sharma,Male,Computer Science,19.0,86.4,70.4,75.7,98.2,76.7,75.2,80.250,Good
79,STU1080,Diya Varma,Male,Electronics,19.0,86.4,80.5,94.3,58.6,74.9,78.6,77.075,Good

SECTION C

In [61]:
# Q16. Student Performance Analysis
# Load Data

df=pd.read_csv('/content/student_performance.csv')

# A. Data Cleaning

df.fillna(df.mean(numeric_only=True),inplace=True)

In [71]:
# B. Feature Engineering

subjects=['Python_Score','SQL_Score','Pandas_Score','NumPy_Score']
df['Average_Score']=df[subjects].mean(axis=1)
df['Pass_Status']=np.where(df['Average_Score'] >= 50,'Pass','Fail')

In [77]:
# C. Analysis

print("Top 5 Students:\n", df.nlargest(5, 'Average_Score')[['Name', 'Average_Score']])
print("\nDepartment having the highest average score:", df.groupby('Department')['Average_Score'].mean().idxmax())
print("\nAttendance by Department:\n\n", df.groupby('Department')['Attendance'].mean())
print("\nNumber of students passed and failed:\n\n", df['Pass_Status'].value_counts())

Top 5 Students:
             Name  Average_Score
10      Diya Das         95.625
61  Kiran Pillai         95.200
8     Diya Menon         92.125
16  Rahul Thomas         89.350
35    Maya Menon         87.800

Department having the highest average score: Electronics

Attendance by Department:

 Department
 Data Science       76.700000
Commerce            77.437500
Computer Science    82.768025
Computer science    92.100000
Data Science        82.076768
Electronics         80.576923
data science        81.672727
Name: Attendance, dtype: float64

Number of students passed and failed:

 Pass_Status
Pass    72
Fail     8
Name: count, dtype: int64

In [84]:
# D. Summary DataFrame

summary_df=df.groupby('Department').agg(Total_Students=('Student_ID','count'),
                                        Average_Score=('Average_Score','mean'),
                                        Average_Attendance=('Attendance','mean'),
                                        Pass_Count=('Pass_Status',lambda x: (x =='Pass').sum()),
                                        Fail_Count=('Pass_Status',lambda x: (x =='Fail').sum())).reset_index()
print("\nSummary:\n", summary_df)

Summary:
          Department  Total_Students  Average_Score  Average_Attendance  \
0     Data Science                1      59.200000           76.700000
1          Commerce               8      68.806931           77.437500
2  Computer Science              29      70.515296           82.768025
3  Computer science               1      53.843590           92.100000
4      Data Science              27      70.671783           82.076768
5       Electronics              13      74.063462           80.576923
6      data science               1      64.725000           81.672727

   Pass_Count  Fail_Count
0           1           0
1           8           0
2          24           5
3           1           0
4          24           3
5          13           0
6           1           0